behaviors:
  MoveCube:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 1000

environment_parameters:
  size:
    curriculum:
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: MoveCube
          signal_smoothing: true
          threshold: .99
          min_lesson_length: 5
        value: 5
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: MoveCube
          signal_smoothing: true
          threshold: .95
          min_lesson_length: 4
        value: 7
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: MoveCube
          signal_smoothing: true
          threshold: .95
        value: 9
      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: MoveCube
          signal_smoothing: true
          threshold: .95
        value: 11
      - name: Lesson5
        completion_criteria:
          measure: reward
          behavior: MoveCube
          signal_smoothing: true
          threshold: .95
        value: 13
      - name: Lesson6
        value: 15
        